# Generated by Django 4.1.2 on 2023-03-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
