# Generated by Django 4.1.2 on 2023-03-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_information_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
